Branch.create!([
  {branch_id: "A01", description: "A01"},
  {branch_id: "END", description: "Placeholder"}
])
Link.create!([
  {page_id: "A01.SCS.01", child_id: "A01.SCS.02", order: 1, body: "Keep on up the street. "},
  {page_id: "A01.SCS.01", child_id: "END", order: 2, body: "Check out the alley. "},
  {page_id: "A01.SCS.02", child_id: "A01.SCS.03a", order: 1, body: "Press the buzzer. "},
  {page_id: "A01.SCS.02", child_id: "A01.SCS.03b", order: 2, body: "Keep on up the street. "},
  {page_id: "A01.SCS.03a", child_id: "A01.SCS.03b", order: 1, body: "Continue towards the Indian place."},
  {page_id: "A01.SCS.03a", child_id: "A01.NNM.b01", order: 2, body: "Press the buzzer again."},
  {page_id: "A01.SCS.03a", child_id: "END", order: 3, body: "Go back to the alley bar. "},
  {page_id: "A01.SCS.03b", child_id: "A01.SCS.04", order: 1, body: "Keep walking. "},
  {page_id: "A01.SCS.03b", child_id: "END", order: 2, body: "Let them lead you. "},
  {page_id: "A01.SCS.04", child_id: "A01.SCS.05a", order: 1, body: "Go north."},
  {page_id: "A01.SCS.04", child_id: "A01.SCS.05b", order: 2, body: "Go south. "},
  {page_id: "A01.NNM.b01", child_id: "A01.NNM.b02", order: 2, body: "See what else is available. "},
  {page_id: "A01.NNM.b01", child_id: "END", order: 1, body: "Look for something to eat and drink. "},
  {page_id: "A01.NNM.b02", child_id: "END", order: 1, body: "Try the numpad. "},
  {page_id: "A01.NNM.b02", child_id: "END", order: 2, body: "Choose something to eat and drink. "},
  {page_id: "A01.NNM.b02", child_id: "A01.NNM.b03", order: 3, body: "Leave the NewNew-Mart. "},
  {page_id: "A01.NNM.b03", child_id: "A01.NNM.b04a", order: 1, body: "Check out the alley bar"},
  {page_id: "A01.NNM.b03", child_id: "A01.NNM.b04b", order: 2, body: "Go up the street to the restaurant. "},
  {page_id: "A01.NNM.b03", child_id: "A01.SCS.c01", order: 3, body: "Find your way to the river. "},
  {page_id: "A01.SCS.b04b", child_id: "NEW BRANCH", order: 1, body: "Drift"},
  {page_id: "A01.SCS.b04a", child_id: "NEW BRANCH", order: 1, body: "Continue"}
])
Location.create!([
  {location_id: "SCS", description: "Salacity Streets"},
  {location_id: "NNM", description: "NewNewMart"},
  {location_id: "END", description: "Placeholder"}
])
Page.create!([
  {page_id: "A01.SCS.01", branch_id: "A01", location_id: "SCS", body: "The tram comes to a stop, waking you from your reverie. You look around. There’s no one else on board. You don’t know where you are, but you step out onto the street.\nThe wet pavement feels gritty beneath your feet. You pull your collar close around your neck and step away from the carriage as it begins to take off. You listen to the warm buzz of the engines and the squeal of the tracks as it continues its route.\nYou’re not sure what to do now, or where to go. You can’t go home tonight. You may not be able to go home at all. Your phone burns a hole in your pocket, but you leave it where it is, turned off and with the battery removed for good measure.\nYou survey the street. Cold cathode lights make a shimmering cloudscape of the light rain, so bright and dazzling that you’ve gotta squint to see through it. You pick out the familiar logos of a NewNew-Mart and a T-Coin ATM. Beyond those you can make out a restaurant, with some Indian deity standing over it in neon pink and yellow. All of the other street-fronts are shut up and dim, but as you walk towards the shops you glance down a covered alley and see a bar, or lounge, where a few patrons slouch and drink, heads oscillating slowly to sultry bass music.\nYou stop and run your fingers through your hair, inhaling and tasting the rain and concrete.", date: "2015-05-13"},
  {page_id: "A01.SCS.02", branch_id: "A01", location_id: "SCS", body: "You drag your eyes from the alley and your mind from the thought of alcohol, and you keep on up the street towards the shops. You pick up your pace as you feel the rain soaking through your coat.\nYou stop in front of the convenience store. A thin stream of water falls from the sign above the door, and you can see ferns and mosses clustered between the letters. There’s a piece of paper on the sliding door telling you to press the buzzer if you want to get in. There doesn’t seem to be anyone inside.\n", date: "2015-05-13"},
  {page_id: "A01.SCS.03a", branch_id: "A01", location_id: "SCS", body: "You step under the vibrant, leafy sign of the NewNew-Mart and press the buzzer. It buzzes\nYou wait.\nNobody comes.", date: "2015-05-13"},
  {page_id: "A01.SCS.03b", branch_id: "A01", location_id: "SCS", body: "You keep going towards the Indian place, leaving the meagre shelter of the NewNew-Mart's front step. You pass an ATM, but you ignore it for now as you have some change in your pocket. Anyway, they're probably watching your account. They could be watching you right now, for all you know. This thought makes you shudder. You try to keep your eyes from the rooftops and alleyways, fixing them on the restaurant. It's only a short walk, you tell yourself, and then you'll be able to sit down at last. You're looking forward to being inside now, to be warm and dry, and thinking about hot food is making your mouth water already.\nYou duck your head and increase your pace as the rain picks up. The neon deity calls to you, its glow coming blurred through the haze. You have to cross the road and then when you look up again she's there, twice your size, looming over you from the roof of the building. It's a Kali, leering, tongue out, holding a severed head. Her nipples flash red beneath a necklace of skulls, blinking like aircraft wing-tips. She didn't seem so lurid from further down the street. Looking through the big windows at the front of the building you see a group of dark, moustachioed men sitting and eating and drinking at the feet of bare chested dancers. An electronic raga blends in the air with masala and perfume.\nYou realise now that this isn’t a family restaurant but some sort of curry serving strip club hybrid. You've heard of these places actually – there's a Thai one in the citadel. You cringe thinking about what a tacky idea it is, how demeaning it must feel to shake your tits for men as they eat their dinner. Only in Salacity, you hear yourself say.\nYou've been noticed. Two smiling, promising, round-bellied girls in faux assuit shawls and little else are hovering under the awning at the front door. They approach you, take your hands and try to lead you inside.\nThough you’re starving, you’ve never been into a place like this and you’re not sure if it’s wise to go in now. Then again, maybe it would be a good place to lay low for a few hours.\n", date: "2015-05-13"},
  {page_id: "A01.SCS.04", branch_id: "A01", location_id: "SCS", body: "Your stomach growls as it reads your thoughts, feels you chickening out. You frown and gaze longingly at a plate of rice and vibrant red curry, envy the satisfied chewing of the man eating from it. But no, it's just too gross in there – you can't do it.\nYou turn around, dragging your eyes back to the street. The cold, wet street. You think about returning to the NewNew-Mart, but you hate doubling back on yourself so you turn the other way instead. You glance back over your shoulder at the sunset-coloured glow of the citadel, confirming that you're heading directly away from it. The street gets quieter and dimmer the further you go.\n//This leads off into the empty streets. You stop somewhere and think things over.//\n//sit down on a bench out front of an abandoned shop and think about what happened earlier. Recall some particular instance of your escape. Recall your plan to take the stolen data to the Tesla state to try to bargain entry.//\n//The Tesla-run city state is in south-west Nevada. Think about your options: north would take you along the river into the slums, where you might be able to evade detection and cross through to the ungoverned area north of Salacity. From there you would have to find transport. This would be the longer route, but perhaps safer. Otherwise you could go south, cross the river by ferry, and try to get a lift on the old highway. This will get you towards Nevada more directly, but that highway crawls with security.//\n", date: "2015-05-13"},
  {page_id: "A01.SCS.05a", branch_id: "A01", location_id: "SCS", body: "//describe walking until you reach the river, then walking along by the cement fence through industrial wastes. Eventually you spot the east salacity suburban slums and think about them as you get closer and closer to them.//", date: "2015-05-13"},
  {page_id: "A01.SCS.05b", branch_id: "A01", location_id: "SCS", body: "//describe walking through an area of failing street lights, crumbling and collapsed buildings, and hearing strange noises down alleys - banging and clanging sounds, sometimes engine noises. You're very tired and paranoid. At one point all the lights on your street shut off at once and you hide for hours. Eventually the dawn light begins to creep into the sky and you can see again, then you continue your walk towards the ferry.//\n//brief description of the ferry terminal and the old bridge, and anticipation of the journey ahead.//\n", date: "2015-05-13"},
  {page_id: "A01.NNM.b01", branch_id: "A01", location_id: "NNM", body: "You press the buzzer again, longer this time.\nEventually you see a hand rise up from below the counter, take hold of its edge, and a sleepy eyed kid hauls himself up behind it, looking bashful. He rubs his eyes then flicks a switch on the wall and the doors slide open for you.\nYou enter. The kid welcomes you in a flat voice and pretends to look busy inspecting a tin of mints. You walk past him, into the aisles.", date: "2015-05-13"},
  {page_id: "A01.NNM.b02", branch_id: "A01", location_id: "NNM", body: "You peruse the shelves. There’s not much here. There’s a lot of stuff, but all variations on the same few items with different coloured packaging. You keep looking.\nReaching the end of an aisle you find that it’s a dead end. You begin to turn around, but then something catches your eye. There’s a door here, painted the same colour as the wall, and plastered with fliers, stickers and posters such that it camouflages into its surrounds. There’s a chunky metal numpad where the doorknob should be.", date: "2015-05-13"},
  {page_id: "A01.NNM.b03", branch_id: "A01", location_id: "NNM", body: "You politely acknowledge the dozy kid behind the counter before you walk back out the front door, onto the street. The sliding doors close behind you. You glance back through the glass and see the kid disappearing again down behind the counter.\nYou're still thinking about that door for some reason. Probably it's just a store-room back there, but something about it spooked you. You realise now that you didn't get anything to eat or drink, though you had intended at least to look.\nYou hear feet scuff nearby and move out of the doorway to let someone else in. You don't look at their face but you see the shine of their wet shoes as you pass them. Your own shoes are beginning to soak through. No doubt your feet will be pale and wrinkled by the time you can take them off.\nYou wonder where to go next. If you stay out much longer you'll have to accept being damp down to the skin. Your jacket can only absorb so much.\nYou suppose you could go back to that bar you saw down the alley. It would be dry at least, and maybe you could find somewhere to sit down for a while. You're hungry though, and there's that restaurant up the street. You take your T-paper out of your pocket reflexively, smoothing it out to look at the figure in the little window. There's not much there. Maybe not enough for a meal, depending on the pricing in that restaurant.\nYou sigh wearily. You're tired of decisions.\nA ferry sounds its horn. The river can't be far from here. You like the river. It's nice sometimes to go down to it and think. You've never been down on this side of it at night. The citadel must look beautiful, reflected on its surface.", date: "2015-05-13"},
  {page_id: "A01.SCS.b04a", branch_id: "A01", location_id: "SCS", body: "//Go back towards the bar. Step in a puddle on the way. A shadow moves across the street and you can't tell what it is, which gives you a shiver. It vanishes down an alley. Then two more shadows come out of the night, lumbering in your direction. You tense up, expecting thugs or cops or worse. Then they step beneath a wavering streetlight and you can see that it's a guy and a girl, and they're turning into the alley bar. They appear relaxed and confident, and this encourages you. You go straight into the bar behind then, weary now of being outside and eager for warmth and shelter.//", date: "2015-05-13"},
  {page_id: "A01.SCS.b04b", branch_id: "A01", location_id: "SCS", body: "//Go up to the Kali. Someone else is being dragged in by the girls, whilst a suited Asian businessman is stumbling out to vomit in the gutter. You walk past, finding the place unappealing, and your feet take you off into the night.//\n//Soon you feel miserable. You're wet, tired and hungry. Part of you wants to go back to the Kali, but you're too ashamed. It starts to rain more heavily and you take shelter under the awning of an abandoned building. You can see inside through the dusty windows - there's a reception area in there with chairs and a couch. The door opens. You could crash there, you think. Even just for a rest.//\n//Describe going in and turning the dusty cushions over then laying down.//\n", date: "2015-05-13"},
  {page_id: "A01.SCS.c01", branch_id: "A01", location_id: "SCS", body: "//Again it's a matter of whether to go north or south. You can make a little better time in this case, being fed and caffeinated.//", date: "2015-05-13"},
  {page_id: "A01.NNM.d01", branch_id: "A01", location_id: "NNM", body: "//you get some Doritos and a can of black coffee. Both are labelled with a strange alphabet - you think it's Thai. Unreadable packaging is an increasingly common sight as the American market is pandered to less and less by foreign manufacturers. You pay with your T-Coin receipt, using up about half of its value, then you go out and look for somewhere dry to sit down. There's a tram shelter across the street, so you go over there. Then you think about what happened today, and what to do next. Remember plan to take data to Tesla city in Nevada.//", date: "2015-05-13"},
  {page_id: "END", branch_id: "END", location_id: "END", body: "THE END - FOR NOW", date: "2015-05-13"},
  {page_id: "NEW BRANCH", branch_id: "END", location_id: "END", body: "To be continued...", date: "2015-05-13"}
])
